version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: socket.io
    versions:
    - ">= 3.a, < 4"
  - dependency-name: socket.io
    versions:
    - ">= 4.a, < 5"
  - dependency-name: superagent
    versions:
    - "> 3.8.3"
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.2
    - 0.39.1
  - dependency-name: postcss
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.7
    - 8.2.9
  - dependency-name: nock
    versions:
    - 13.0.6
    - 13.0.7
    - 13.0.9
  - dependency-name: pug
    versions:
    - 3.0.2
  - dependency-name: lockfile-lint
    versions:
    - 4.6.2
  - dependency-name: hostenv
    versions:
    - 3.15.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: supertest
    versions:
    - 6.1.2
    - 6.1.3
  - dependency-name: stylelint
    versions:
    - 13.9.0
  - dependency-name: nodemon
    versions:
    - 2.0.7
